name: 'Setup Python + Poetry environment'
description: 'Setup Python + Poetry environment with dependency caching'

inputs:
  python-version:
    required: false
    description: 'Python version'
    default: '3.10'
outputs: {}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - uses: abatilo/actions-poetry@v2

    - name: Cache Poetry virtualenv
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: poetry-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          poetry-${{ runner.os }}-py${{ inputs.python-version }}-

    - name: Configure Poetry to use in-project venv
      run: poetry config virtualenvs.in-project true
      shell: bash

    - name: Install dependencies
      run: poetry install --all-extras
      shell: bash
