name: Verify OpenAPI spec

on:
  pull_request:
    branches:
      - "**"

jobs:
  verify-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install openapi-python-client==0.16.0 click==8.2.1 typer==0.9.*
      - name: Check workflow files
        run: make openapi/generate
        shell: bash
      - id: diffcheck
        shell: bash
        run: |
          CHANGED_FILE=$(git diff --name-only src/okareo_api_client)
          if [ -n "$CHANGED_FILE" ]; then
            echo "Spec does not match code"
            exit 1
          fi
